name: Build x64
on:
  workflow_dispatch
jobs:
  build:
    name: Build
    runs-on: windows-latest
    steps:
      - name: Check out source code
        uses: actions/checkout@v4
        with:
          # needed to calc build number via git log --oneline
          fetch-depth: 0

      - name: Build
        run: |
          .\doit.bat -build-pre-rel
          xcopy "./out/final-prerel/SumatraPDF-prerel-64.exe" "SumatraPDF-prerel-64.exe"
          xcopy "./out/final-prerel/SumatraPDF-prerel-64.zip" "SumatraPDF-prerel-64.zip"
          xcopy "./out/final-prerel/SumatraPDF-prerel-64-install.exe" "SumatraPDF-prerel-64-install.exe"
        
      - name: Publish
        uses: softprops/action-gh-release@v2
        with:
          files: |
            "SumatraPDF-prerel-64.exe"
            "SumatraPDF-prerel-64.zip"
            "SumatraPDF-prerel-64-install.exe"
          tag_name: "prerel-64"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
