name: myDaily
on:
  workflow_dispatch
jobs:
  build:
    name: Build
    #runs-on: SumatraBuilder
    runs-on: windows-latest
    steps:
      - name: Check out source code
        uses: actions/checkout@v4
        with:
          # needed to calc build number via git log --oneline
          fetch-depth: 0

      - name: Build
        run: |
          .\doit.bat -ci
          7z a -tzip "SumatraPDFout.zip" "./out/*"
        
      - name: Publish
        uses: softprops/action-gh-release@v2
        with:
          files: "SumatraPDFout.zip"
          tag_name: "v3.6.0"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
