name: Private Build
on:
  workflow_dispatch
jobs:
  build:
    name: Build
    runs-on: windows-latest
    steps:
      - name: Check out source code
        uses: actions/checkout@v4
        with:
          # needed to calc build number via git log --oneline
          fetch-depth: 0

      - name: build-pre-rel
        run: .\doit.bat -build-smoke

      - name: Get x64 files
        uses: actions/upload-artifact@v4
        with:
          name: spdf-artifacts-64
          path: out/rel64/*.exe
          retention-days: 1

      - name: Get x86 files
        uses: actions/upload-artifact@v4
        with:
          name: spdf-artifacts-32
          path: out/rel32/*.exe
          retention-days: 1
